version: '3'
services:
  dev:
    build: .
    volumes:
      - .:/root/workspace
      # https://code.visualstudio.com/docs/remote/containers-advanced#_avoiding-extension-reinstalls-on-container-rebuild
      - vs-server:/root/.vscode-server/extensions
volumes:
  vs-server: {}